# Generated by Django 4.0.2 on 2022-02-01 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='language',
        ),
    ]
