# Generated by Django 4.0.2 on 2022-02-01 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_remove_challenge_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='description',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='output_parameter',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='test_input_parameter',
        ),
        migrations.AddField(
            model_name='challenge',
            name='solution',
            field=models.TextField(default='-'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='challenge',
            name='task',
            field=models.CharField(choices=[('2NS', 'Two Number Sum'), ('3NS', 'Three Number Sum'), ('4NS', 'Four Number Sum')], default='-', max_length=3),
            preserve_default=False,
        ),
    ]
