# Generated by Django 4.0.2 on 2022-02-01 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0003_remove_challenge_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='language',
            field=models.CharField(choices=[('PY', 'Python'), ('JS', 'JavaScript'), ('TS', 'TypeScript'), ('C#', 'C#')], default='PY', max_length=2),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='task',
            field=models.CharField(choices=[('2NS', 'Two Number Sum'), ('3NS', 'Three Number Sum'), ('4NS', 'Four Number Sum')], default='2NS', max_length=3),
        ),
    ]
